print("╔"+"═"*30+"╗")
print("║         Halı Yıkama V1       ║")
print("║                              ║")
print("║        1-Müşteri Kayıt       ║")
print("║        2-Müşteri Ara         ║")
print("║        3-Bilgi Güncelle      ║")
print("║        4-Bilgi Sil           ║")
print("║                              ║")
print("║      Seçiminizi Yapınız      ║")
print("╚"+"═"*30+"╝")
